# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0bec1de2c0abb247374ce3ad8b0c06e933349ce9888716abc6c56be01d87c883af38f48b5bbed66236c3b1a765df6d23e75143a9a759c7544ea98d2f6946db

test:
  secret_key_base: e079b9223cc51d79b2898082d1eda7c60361e2572265d9a3c218574fca524a4089122d0874d7249d1d7daae4c22dff8f63c04b14f1dc566c20f751d9210b5940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
